 # Copyright (c) 2022, salesforce.com, inc.
 # All rights reserved.
 # SPDX-License-Identifier: BSD-3-Clause
 # For full license text, see the LICENSE file in the repo root or https://opensource.org/licenses/BSD-3-Clause

datasets:
  llava_box_caption_aibeeQA:
    # data_dir: ${env.data_dir}/datasets
    data_type: images # [images|videos|features]

    build_info:
      # Be careful not to append minus sign (-) before split to avoid itemizing
      annotations:
        train:
          url:
              - ""
              - ""
          storage:
              - eventgpt/annotations/label_result_530_llava-style-box_caption_en.json
              - eventgpt/annotations/label_result_530_llava-style-box_caption_en.json
        val:
          url:
              # TODO make this order insensitive
              - ""
              - ""
              - ""
              - ""
          storage:
              - eventgpt/annotations/label_result_530_llava-style-box_caption_en.json
              - eventgpt/annotations/answer_list.json
              - eventgpt/annotations/v2_OpenEnded_mscoco_val2014_questions.json
              - eventgpt/annotations/v2_mscoco_val2014_annotations.json
        test:
          url:
              - ""
              - ""
          storage:
              - eventgpt/annotations/label_result_530_llava-style-box_caption_en.json
              - eventgpt/annotations/answer_list.json
      images:
          storage: eventgpt/images/
